# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FreeClicker-iOS' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'QRCodeReader.swift', '~> 7.2.0'
  pod 'SwiftyJSON'
  # Pods for FreeClicker-iOS

  target 'FreeClicker-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FreeClicker-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
